name: Ha-expert-Client
version: "0.2.26"
slug: talkha_client
description: Full remote service agent for TalkHa and TalkHaLokal
url: https://github.com/fc5tomasz/talkha-client-addon
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: manager
arch:
  - aarch64
  - amd64
  - armv7
  - i386
map:
  - type: homeassistant_config
    read_only: false
options:
  ha_token: ""
  client_id: ""
  operator_url: ""
schema:
  ha_token: str
  client_id: str
  operator_url: str
